services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092" # External access (Windows)
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # 1. INTERNAL: Used by Producer/Consumer containers (kafka:29092)
      # 2. EXTERNAL: Used by Windows/Localhost (localhost:9092)
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  producer:
    build: .
    depends_on:
      - kafka
    # Connects to the INTERNAL port (29092)
    command: ["sh", "-c", "sleep 10 && python producer.py"]
    environment:
      KAFKA_BROKER: "kafka:29092"

  consumer:
    build: .
    depends_on:
      - kafka
    # Connects to the INTERNAL port (29092)
    command: ["sh", "-c", "sleep 10 && python consumer.py"]
    environment:
      KAFKA_BROKER: "kafka:29092"